"""Add new fields to business_info

Revision ID: d9757adc8ef9
Revises: 0011_add_handoff_summary
Create Date: 2026-06-17 14:19:36.530419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9757adc8ef9'
down_revision: Union[str, Sequence[str], None] = '0011_add_handoff_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_info', sa.Column('politica_cambios_devoluciones', sa.Text(), nullable=True))
    op.add_column('business_info', sa.Column('tiempos_entrega', sa.Text(), nullable=True))
    op.add_column('business_info', sa.Column('formas_pago', sa.Text(), nullable=True))
    op.add_column('business_info', sa.Column('telefono_oficina', sa.String(), nullable=True))
    op.add_column('business_info', sa.Column('requisitos_cotizacion', sa.Text(), nullable=True))
    op.create_index(op.f('ix_conversations_assigned_to_user_id'), 'conversations', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel_identifier'), 'conversations', ['channel_identifier'], unique=False)
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.drop_index(op.f('idx_stage_rules_pipeline_id'), table_name='stage_rules')
    op.drop_index(op.f('idx_stage_rules_stage_id'), table_name='stage_rules')
    op.drop_index(op.f('idx_tasks_contact_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_opportunity_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_opportunity_id'), 'tasks', ['opportunity_id'], unique=False)
    op.create_index(op.f('idx_tasks_contact_id'), 'tasks', ['contact_id'], unique=False)
    op.create_index(op.f('idx_stage_rules_stage_id'), 'stage_rules', ['stage_id'], unique=False)
    op.create_index(op.f('idx_stage_rules_pipeline_id'), 'stage_rules', ['pipeline_id'], unique=False)
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel_identifier'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_to_user_id'), table_name='conversations')
    op.drop_column('business_info', 'requisitos_cotizacion')
    op.drop_column('business_info', 'telefono_oficina')
    op.drop_column('business_info', 'formas_pago')
    op.drop_column('business_info', 'tiempos_entrega')
    op.drop_column('business_info', 'politica_cambios_devoluciones')
    # ### end Alembic commands ###
